repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
        exclude: "{{cookiecutter.project_slug}}/"
      - id: check-yaml
        exclude: "{{cookiecutter.project_slug}}/"
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.14"
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: "({{cookiecutter.project_slug}}/|hooks/)"
      - id: ruff-format
        exclude: "({{cookiecutter.project_slug}}/|hooks/)"
