# This workflow will install the package with UV,
# run the tests on multiple Python versions,
# and upload the results on codecov.
name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '30 5 1,15 * *'
env:
  NUMBA_DISABLE_JIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v5
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.2"

    - name: Run tests
      run: |
        uv sync --all-extras
        uv run pytest

    - name: Upload coverage reports to Codecov with GitHub Action on Python 3.12
      uses: codecov/codecov-action@v4
      if: {% raw %}${{ matrix.python-version == '3.12' }}{% endraw %}
      with:
        file: ./coverage.xml
        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %} # required
