# This workflow will generate the docs on each push,
# and publish them on GitHub Pages if the branch is the main one.
# To avoid size explosion, only the current version of pages is kept.

name: docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: '3.6.3'

      - name: Build Sphinx documentation
        run: |
          uv sync --all-extras
          uv run sphinx-build -a -E -b html docs build

      - name: Deploy Sphinx documentation on Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          branch: gh-pages
          folder: build/
          single-commit: true
